server:
  port: 8080

spring:
  application:
    name: post-manager 

logging:
  level:
    com.plamason.postmanager: DEBUG  # 패키지별 로그 레벨 설정
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 