server:
  port: 8080

spring:
  application:
    name: post-manager
  cache:
    type: simple
  datasource:
    url: jdbc:h2:file:./data/postmanagerdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      encoding: UTF-8
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

logging:
  level:
    com.plamason.postmanager: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 